### ISSUE TITLE
Availability of clientJoin/Part events and signaling across transcluded webstrates

### ISSUE THREAD

**Issue by thiemok** [Webstrates/Webstrates#16]
Hello,
assuming the following setup:
```
Webstrate A with some client specific transient data
Webstrate B transcluding A
```
Is it possible to subscribe to clientJoin/Part events on `A` in such a way, that `B` is aware of `A`'s clients and is able to signal a client connected to `A` to exchange some of its transient data?
I tried both subscriting on the iframe itself and it's contentWindow property.

Regards,
thiemo

**Comment by kbadk** [comment]
Yes, doing this should be quite straightforward. I cooked up a little example:

In webstrate B transcluding webstrate A (in an iframe `#iframe`), we have:

```javascript
webstrate.on("loaded", function() {
  var iframe = document.getElementById("iframe");
  iframe.webstrate.on("transcluded", function() {
    iframe.contentWindow.webstrate.on("clientJoin", function(clientId) {
      console.log("Client joined");
      iframe.contentWindow.webstrate.signal("Hello, world!", clientId);
    });
  });
});
```
When a client joins the transcluded webstrate, it sends a signal to the client.

In the other webstrate, we listen for these signals:

```javascript
webstrate.on("loaded", function() {
  webstrate.on("signal", function(msg) {
    console.log("Received signal:", msg);
  });
});
```

I hope this helps.

**Comment by thiemok** [comment]
Thanks, its working now! I did not wait for the transclusion to finish, before adding the listeners.

**Comment by kbadk** [comment]
Great!

Note that we are waiting for transclusion on the iframe element in webstrate B (`iframe.webstrate.on("transcluded", ...)`), but attaching the `clientJoin` listener to the window element in webstrate A (`iframe.contentWindow.webstrate.on("clientJoin", ...)`).

Adding a listener for `clientJoin` events on the iframe in webstrate B would have resulted in an error ("On-event 'clientJoin' does not exist").

Likewise, attempting to add it with `iframe.contentWindow.webstrate` before the iframe had loaded would also resul in an error, because the `webstrate` can't be defined before the page has loaded.
