### ISSUE TITLE
Time stamps on tags

### ISSUE THREAD

**Issue by cklokmose** [Webstrates/Webstrates#25]
Provide tags (accessed through ?tags) with time stamps like:
`{
"v": 1953,
"label": "release",
"timestamp": "Sat Jun 03 2017 10:20:40 GMT+0200 (CEST)"
}`

**Comment by kbadk** [comment]
`?tags` now returns a list of tags including timestamps, e.g.

```javascript
{
    "v": 25,
    "label": "Session Mon May 15 2017 23:13:59 GMT+0200 (CEST)",
    "timestamp": "2017-05-15T21:13:59.000Z"
},
```

This format is used, because it's more concise than the suggested, but also because it's the default format returned by MongoDB's `ObjectId.getTimestamp()`.

To obtain the timestamp in the requested format, one could simply pass it to JavaScript's [Date constructor](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date):

```
> new Date("2017-05-15T21:13:59.000Z").toString()
"Mon May 15 2017 23:13:59 GMT+0200 (CEST)"
```
