### ISSUE TITLE
webstrate.user.signal bug

### ISSUE THREAD

**Issue by jensemil** [Webstrates/Webstrates#70]
According to the [user guide on signalling](https://webstrates.github.io/userguide/api/signaling.html), there is supposed to be a signal function on the user object for sending a signal to the clients associated with a user.

However, it currently seems like it does not exist:
![image](https://user-images.githubusercontent.com/6105088/40530366-c405afc6-5ff8-11e8-9e73-504fa311bd50.png)

**Comment by kbadk** [comment]
When I did the [complete webpack rewrite](https://github.com/Webstrates/Webstrates/commit/23c1ef8958a14a16fc4fbc0a4be866d039acf593) back in June 2017, I was too eager to get it out there that I didn't implement the user signaling, but just put it on the todo where it has been hiding out until now, because nobody has needed. So now that they you do, I've just re-implemented it!

I apologize for the confusion the discrepancy between the documentation and implementation might have caused.
