### ISSUE TITLE
The webstrate.clients array sometimes missing a client or has duplicates

### ISSUE THREAD

**Issue by raedle** [Webstrates/Webstrates#88]
The `webstrate.clients` list is sometimes missing a client id or has duplicate client ids. This frequently happens inside Codestrates, but can also be replicated on an empty webstrate (see [Video on Dropbox](https://www.dropbox.com/s/jxuf9kjqvl134kk/Webstrates%20Clients%20Bug.mp4?dl=0)).

Steps to replicate:

1. Create an empty webstrate
2. Open webstrate in a second window
3. Then log the list of clients (`webstrate.clients`) in both windows
4. Frequently reload one of the two windows and log the `webstrate.clients` in both again.
5. Repeat step 4. until one client is missing or list of clients has duplicates.

**Comment by kbadk** [comment]
Thanks for thorough bug report! I was able to reproduce the issue demonstrated in the video (albeit not locally) and have subsequently fixed it. The issue of duplicating client ids, however, I was unable to reproduce.

If you can reproduce the other issue, I'd be happy to take another look at it.

**Comment by raedle** [comment]
Thanks for following up on this issue.

I tested it again, and it seems that missing client ids is not a problem anymore. However, the client list now has orphan client ids for a while when the connection drops for a few seconds (see https://www.dropbox.com/s/t2czlb3vfmjs33e/Orphan%20client%20ids%20in%20client%20list.mp4?dl=0). I guess client ids are in the list until the disconnected clients timeout?!

I provoked this behavior by switching the connection from WiFi to a mobile hotspot.

Also, the documentation says
> The first Client ID in the list will always be the client’s own Client ID.

But that's not the case. Is the order of client ids in the list random?

**Comment by kbadk** [comment]
It is indeed the connection timeout happening. Waiting for the connection timeout is standard practice for non-critical applications (if Skype crashes, you also linger in the contact list for a little), so let's continue to rely on that.

However, after playing around with it for a little, I agree that the timeout is too long. According to [the documentation](https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback), the socket timeout is 2 minutes. (The OS may timeout the connection sooner though).

I've changed it to a 30 second timeout now. Does that work for you? Unless there's a compelling argument, I'm hesitant to lower it further as it will cause clients on spotty networks to drop in and out of a session again and again. Likewise, if your tablet goes to sleep while in a Webstrate, you risk disconnecting before unlocking it again if we lower it further, I think.

>The first Client ID in the list will always be the client’s own Client ID.

I'll remove that line from the documentation. That hasn't been true for years. Initially I designed it this way, because there was no `webstrate.clientID` if I recall correctly. It was an odd design choice I later regretted, and I guess I must have accidentally copied it over from the old documentation. It hasn't been true for as long as the current documentation has existed.

The order of `webstrate.clients` isn't entirely random: it should be the order in which clients joined, the oldest client will be first in the list, but there's no guarantee. I.e. if two clients join exact simultaneously on different threads on a multi-threaded webstrate server, I suspect it may be possible for the order of the list to be out of sync, though I haven't experienced it.
