### ISSUE TITLE
Installing webstrates on Ubuntu

### ISSUE THREAD

**Issue by jtheis1993** [Webstrates/Webstrates#91]
I get everything installed and running on webstrates.sinoscansites.com, but whatever I do, I simply cannot get around the error: 
MongoError: not authorized on admin to execute command { find: "webstrates", filter: { _id: "frontpage" }, projection: { _m: 0, _o: 0 }, limit: 1, $db: "admin" }

What is this caused by? My user on Atlas DB has full rights

**Comment by kbadk** [comment]
Are you able to modify the database manually using something like Robo 3T or the command line? Have you added the credentials in the mongodb address string in the config file?

This does not seem to be a problem with Webatrates.

**Comment by jtheis1993** [comment]
Yes, I can modify the database with MongoDB Compass.
Yes, i'm not sure if it's correct though, but it's pasted from Atlas and with credentials: 
 "db": "mongodb+srv://myUsernamel:myPassword@cluster0-l1jy9.azure.mongodb.net/test?retryWrites=true",

Do I need to put it in another format? And what do I need to edit manually in the DB?

**Comment by kbadk** [comment]
Are you using the free tier on Atlas? I'm only vaguely familiar with Atlas, but it'd appear that the free tier is severely limited. Is there any particular reason why you're not hosting your own MongoDB instance?

**Comment by kbadk** [comment]
After playing around with Atlas, it'd appear that the connection string you're using is for version 3.0 or later of the Node.js driver. Webstrates is using version 2.1. However, Atlas does not appear to support anything prior to 2.2. So run `npm install mongodb@2.2` from the Webstrates folder, and then use the 2.2 connection string provided by Atlas instead of the 3.0 connection string.

Also, I'd suggest you selfhost your MongoDB database along with your Webstrates server as you'll get much better performance.
