### ISSUE TITLE
Return URL after auth login

### ISSUE THREAD

**Issue by svnhub** [Webstrates/Webstrates#92]
Currently users who use the /auth/xyz path to authenticate are sent to the path of the "Referer" HTTP-header (or "/") after successful authentication. Since Referer is optional and fully controlled by the client browser it is difficult to support preservation of this header in complex multi-step login systems. In fact, in the specific use case that prompted this issue the Referer field is updated as follows during the login process:
1) User is on webstrate A, referer is some other webstrate X
2) User clicks /auth/au link, referer is now correctly webstrate A
3) Redirect to login system, referer is still webstrate A
4) User selects login method, say Google, referer is changed to login system
5) Login method performs actual login, referer is now Google
6) Redirect back to consent page, users accepts, referer is now consent page
7) Redirect back to callback, referer is consent page
8) /auth/au/callback redirects to Referer causing an infinite loop between 7 and 8

Additionally, in some cases it may make sense to start on webstrate A, perform a login and then end up on webstrate B rather than back at A.

Suggested solution:
Would it be possible to optionally specify a returnURL when going to the /auth/xyz path that is then stored in the session and later retrieved when the user returns via the callback url? This returnURL could then potentially default to what the Referer header was set to when /auth/xyz was called if it wasn't explicitly given. If the header wasn't set and no returnURL was explicitly given then "/" could be assumed.

**Comment by kbadk** [comment]
Thanks for the report. I can't reproduce it myself, but it makes perfect sense that this could occur.

I've fixed it now (hopefully), so that you won't end up in an infinite recursion. We now use a session cookie to save the referer in the beginning, so all that bouncing around between endpoints doesn't mess things up. When we're being redirected back to the Webstrates server, we know the original referer through said session.

I don't too much like the idea of just sending people off in whatever direction we want, so instead of defining a returnURL, you can now instead specify the webstrateId to return to in the query string, e.g. `/auth/github?webstrateId=myWebstrate`. If you don't specify a webstrateId, you'll be sent back to where you came from. 

I hope that will suffice. If not – and there's a reasonable use case for being able to specify complete URLs – I'm open to changing it.

**Comment by svnhub** [comment]
Nice solution, and fully agree on avoiding arbitrary URLs in the return - a webstrate ID should suffice
